# Usa la imagen de Node como base. Cambia `22` según la versión que necesites.
FROM node:22

# Configura el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y el package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código al contenedor
COPY . .

# Expone el puerto 5173 en el contenedor
EXPOSE 5173

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]
